services:
  # The Grat Relay Service
  - type: web
    name: grat-relay
    runtime: docker
    dockerContext: .
    dockerfilePath: packages/server/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: NETWORK
        value: testnet
      - key: DATABASE_URL
        fromDatabase:
          name: grat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: grat-redis
          property: connectionString
      - key: CHANNEL_SEED_PHRASE
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true

  # The Redis Instance
  - type: redis
    name: grat-redis
    plan: free
    ipAllowList: []

# The PostgreSQL Database
databases:
  - name: grat-db
    plan: free
